### ISSUE TITLE
This property does not take the value you have set to it. It can take:

### ISSUE THREAD

**Issue by ProfJoanna** [Ronak2723/mtm6201-midterm#3]
https://github.com/Ronak2723/mtm6201-midterm/blob/dd5f2e9f023b8bed539e9d6c2198f40cfd60e313/styles.css#L36

**Comment by Ronak2723** [comment]
Can i get some time for it i am little bit out


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Professor Joanna D. ***@***.***>
Sent: Friday, April 14, 2023 6:27:08 PM
To: Ronak2723/mtm6201-midterm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Ronak2723/mtm6201-midterm] This property does not take the value you have set to it. It can take: (Issue #3)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

https://github.com/Ronak2723/mtm6201-midterm/blob/dd5f2e9f023b8bed539e9d6c2198f40cfd60e313/styles.css#L36

**Comment by ProfJoanna** [comment]
You don't have to make any updates to your code right now. This is just feedback for your future.
